name = 'Decisions & Dragons'
license = 'MIT'
description = 'Theme for the reinforcement learning website www.decisionsanddragons.com'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/jmacglashan/decisions_and_dragons'

# If you have a running demo of the theme
demosite = 'www.decisionsanddragons.com'

# Taxonomy terms
tags = ['blog']
features = []

# If the theme has a single author
[author]
name = 'James MacGlashan'
homepage = 'www.decisionsanddragons.com'
